# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: path/to/cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-build-
